version: "2"

linters:
  # Start from an empty set and only enable the linters we want.
  default: none
  enable:
    - govet
    - staticcheck
    - godot
    - unused
  settings:
    godot:
      # Require doc comments to end with a period.
      scope: declarations
      exclude:
        # Exclude lines that start a list or contain code examples.
        - '^\s*-'
        - 'TODO'
        - 'NOTE'
