version: 2

project_name: coragent

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/coragent
    binary: coragent
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X coragent/internal/cli.Version={{.Version}}
      - -X coragent/internal/cli.Commit={{.Commit}}
      - -X coragent/internal/cli.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

